services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1704
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # redis:
  #   image: redis:6.0
  #   container_name: redis-cache
  #   ports:
  #     - "6379:6379"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env # đường dẫn TƯƠNG ĐỐI từ file docker-compose.yml
    depends_on:
      - mysql

volumes:
  mysql-data:
